import type { ThemeDefinition } from "xmlui";

export const WebsiteTheme: ThemeDefinition = {
  id: "animo-website",
  name: "Animo Website",
  extends: "xmlui",
  color: "$color-primary-500",
  themeVars: {
    // Keep this aligned with the main web app: define const-color atoms
    // and consume tone-aware color-* aliases below. XMLUI inverts the
    // color-* scale in dark tone, then the tones block handles the few
    // semantic surfaces that need hand-tuned contrast.
    "const-color-primary-50": "#EAF3F1",
    "const-color-primary-100": "#D5E7E3",
    "const-color-primary-200": "#A7D0C9",
    "const-color-primary-300": "#7AB8AE",
    "const-color-primary-400": "#5DA39D",
    "const-color-primary-500": "#3F8F8C",
    "const-color-primary-600": "#357773",
    "const-color-primary-700": "#2A5F5B",
    "const-color-primary-800": "#1F4744",
    "const-color-primary-900": "#162F2D",
    "const-color-primary-950": "#0F1F1D",

    "const-color-surface-0": "#FFFFFF",
    "const-color-surface-50": "#FAF8F6",
    "const-color-surface-100": "#F0EDEA",
    "const-color-surface-200": "#E0DCD7",
    "const-color-surface-300": "#C2BDB7",
    "const-color-surface-400": "#9D9893",
    "const-color-surface-500": "#76716D",
    "const-color-surface-600": "#544F4B",
    "const-color-surface-700": "#3D3934",
    "const-color-surface-800": "#2C2925",
    "const-color-surface-900": "#1E2328",
    "const-color-surface-950": "#14181C",
    "const-color-surface-1000": "#0A0C0F",

    "const-color-warn-50": "#FEF6E6",
    "const-color-warn-100": "#FCEBC8",
    "const-color-warn-200": "#F9CE8C",
    "const-color-warn-300": "#F6B95C",
    "const-color-warn-400": "#F4AE45",
    "const-color-warn-500": "#F2A82F",
    "const-color-warn-600": "#D49118",
    "const-color-warn-700": "#A36F0E",
    "const-color-warn-800": "#7C5408",
    "const-color-warn-900": "#553905",
    "const-color-warn-950": "#3B2604",

    "const-color-danger-50": "#FFE7E5",
    "const-color-danger-100": "#FFCFCB",
    "const-color-danger-200": "#FFB0A8",
    "const-color-danger-300": "#FF9485",
    "const-color-danger-400": "#FF8170",
    "const-color-danger-500": "#FF6F61",
    "const-color-danger-600": "#E8554A",
    "const-color-danger-700": "#C8412F",
    "const-color-danger-800": "#9C2F22",
    "const-color-danger-900": "#6E2017",
    "const-color-danger-950": "#48140E",

    backgroundColor: "$color-surface-50",
    "backgroundColor-primary": "$color-surface-50",
    fontFamily: "Sora,system-ui,-apple-system,Segoe UI,sans-serif",
    fontSize: "15px",
    "fontFamily-monospace": "Menlo,Monaco,Consolas,Liberation Mono,Courier New,monospace",
    "maxWidth-content-App": "100%",
    "maxWidth-App": "100%",
    "paddingVertical-Pages": "0",
    "paddingHorizontal-Pages": "0",
    "gap-Pages": "0",
    "textColor-Text": "$color-surface-700",
    "textColor-Heading": "$color-surface-900",

    "color-page-bg": "$color-surface-50",
    "color-header-bg": "$color-surface-0",
    "color-section-bg": "$color-surface-0",
    "color-panel": "$color-surface-0",
    "color-panel-deep": "$color-surface-0",
    "color-sidebar-bg": "$color-surface-50",
    "color-field-bg": "$color-surface-0",
    "color-text": "$color-surface-900",
    "color-muted": "$color-surface-600",
    "color-subtle": "$color-surface-500",
    "color-border": "$color-surface-200",
    "color-border-strong": "$color-surface-300",
    "color-accent": "$color-primary-500",
    "color-accent-soft": "$color-primary-600",
    "color-on-accent": "$color-surface-0",
    "color-warn": "$color-warn-500",
    "color-nav-active-bg": "$color-primary-50",
    "color-nav-active-border": "$color-primary-200",
    "color-event-neutral-bg": "$color-primary-100",
    "shadow-mockup": "0 20px 60px rgba(30, 35, 40, 0.14)",
    "shadow-section": "0 18px 45px rgba(30, 35, 40, 0.07)",

    "hero-image": "url(/resources/hero-calendar.png)",

    "backgroundColor-Card": "$color-panel",
    "backgroundColor-Card--hover": "$color-panel",
    "borderColor-Card": "$color-border",
    "borderRadius-Card": "8px",
    "boxShadow-Card": "none",
    "boxShadow-Card--hover": "none",

    "backgroundColor-Button-primary-solid": "$color-accent",
    "backgroundColor-Button-primary-solid--hover": "$color-primary-400",
    "backgroundColor-Button-primary-solid--active": "$color-primary-600",
    "borderColor-Button-primary-solid": "$color-accent",
    "textColor-Button-primary-solid": "$color-on-accent",
    "backgroundColor-Button-secondary-outlined": "transparent",
    "backgroundColor-Button-secondary-outlined--hover": "$color-surface-100",
    "borderColor-Button-secondary-outlined": "$color-border-strong",
    "borderColor-Button-secondary-outlined--hover": "$color-surface-400",
    "textColor-Button-secondary-outlined": "$color-text",
    "textColor-Button-secondary-outlined--hover": "$color-text",
    "borderRadius-Button": "6px",
    "textDecorationLine-Link": "none",
    "textColor-Link": "$color-muted",
    "textColor-Link--hover": "$color-text",
  },
  tones: {
    light: {
      themeVars: {
        "backgroundColor-Card": "$color-surface-0",
        "backgroundColor-Card--hover": "$color-surface-0",
        "boxShadow-Card": "none",
      },
    },
    dark: {
      themeVars: {
        backgroundColor: "#0A0C0F",
        "backgroundColor-primary": "#0A0C0F",
        "textColor-Text": "rgb(250 248 246 / 0.92)",
        "textColor-Heading": "#FAF8F6",

        "color-page-bg": "#0A0C0F",
        "color-header-bg": "#0A0C0F",
        "color-section-bg": "rgb(20 24 28 / 0.78)",
        "color-panel": "#1E2328",
        "color-panel-deep": "#14181C",
        "color-sidebar-bg": "rgb(30 35 40 / 0.72)",
        "color-field-bg": "rgb(250 248 246 / 0.03)",
        "color-text": "#FAF8F6",
        "color-muted": "rgb(250 248 246 / 0.68)",
        "color-subtle": "rgb(250 248 246 / 0.46)",
        "color-border": "rgb(250 248 246 / 0.10)",
        "color-border-strong": "rgb(250 248 246 / 0.18)",
        "color-accent": "#3F8F8C",
        "color-accent-soft": "#A7D0C9",
        "color-on-accent": "#FAF8F6",
        "color-warn": "#F2A82F",
        "color-nav-active-bg": "rgb(63 143 140 / 0.18)",
        "color-nav-active-border": "rgb(63 143 140 / 0.34)",
        "color-event-neutral-bg": "rgb(250 248 246 / 0.07)",
        "shadow-mockup": "0 24px 80px rgba(0, 0, 0, 0.44)",
        "shadow-section": "none",

        "hero-image": "url(/resources/hero-calendar-dark.png)",

        "backgroundColor-Card": "rgb(30 35 40 / 0.72)",
        "backgroundColor-Card--hover": "rgb(30 35 40 / 0.72)",
        "borderColor-Card": "rgb(250 248 246 / 0.10)",
        "boxShadow-Card": "none",
        "boxShadow-Card--hover": "none",

        "backgroundColor-Button-primary-solid": "#3F8F8C",
        "backgroundColor-Button-primary-solid--hover": "#5DA39D",
        "backgroundColor-Button-primary-solid--active": "#357773",
        "borderColor-Button-primary-solid": "#3F8F8C",
        "textColor-Button-primary-solid": "#FAF8F6",
        "backgroundColor-Button-secondary-outlined": "transparent",
        "backgroundColor-Button-secondary-outlined--hover": "rgb(250 248 246 / 0.06)",
        "borderColor-Button-secondary-outlined": "rgb(250 248 246 / 0.18)",
        "borderColor-Button-secondary-outlined--hover": "rgb(250 248 246 / 0.28)",
        "textColor-Button-secondary-outlined": "#FAF8F6",
        "textColor-Button-secondary-outlined--hover": "#FAF8F6",
        "textColor-Link": "rgb(250 248 246 / 0.68)",
        "textColor-Link--hover": "#FAF8F6",
      },
    },
  },
};

export default WebsiteTheme;
